---
title: "Consistency Experiment"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library('rerf')
library('ggplot2')
library('stats')
```

### Sampling process
* Uniformly sample from {1, 2, 3}
* Sample from a unit square for each point
* Determine Y based on position of the points in the unit square

```{r}
createData <- function(n, seed) {
  set.seed(seed)
  # Determine which square each sample lives in
  squares <- sample(c(1, 2, 3), n, replace = TRUE)

  Y <- integer(n)
  X <- matrix(0, nrow = n, ncol = 2)
  
  for (i in 1:n) {
    square <- squares[i]
    point <- runif(2, min = square- 1, max = square)
    
    X[i, ] <- point
    if (square == 1) {
      if (point[1] > 0.5) {
        Y[i] <- 1
      }
    } else if (square == 2) {
      if ((point[1] <= 1.5 & point[2] > 1.5) | (point[1] > 1.5 & point[2] <= 1.5)) {
        Y[i] <- 1
      }
    } else if (square == 3) {
      if (point[2] <= 2.5) {
        Y[i] <- 1
      }
    }
  }

  return(list(X = X, Y = factor(Y)))
}

visualizeData <- function(n) {
  out <- createData(n, seed = NULL)
  X <- out$X
  Y <- out$Y
  
  qplot(X[, 1], X[, 2], color = Y) + labs(x = "X1", y = "X2",  title = paste0("Visualization of sample data (n=", n, ")"))
}

visualizeData(1000)
```

```{r}
n.samples <- 2^(4:14)

runExperiment <- function(random.matrix, n.samples, seed = 20180828) {

  oob.errors <- integer(length(n.samples))
  
  for (i in 1:length(n.samples)) {
    res <- createData(n.samples[i], seed)
    X <- res$X
    Y <- res$Y
    
    p <- ncol(X)
    d <- ceiling(sqrt(p))
    #d <- 1
    rho <- 1 / p
    prob <- 0.5
    
    mat.options <- list(p = p, d = d, random.matrix = random.matrix, rho = rho, prob = prob)
    
    print(paste("Running forest with", n.samples[i], "samples"))
  
    forest <- RerF(X, Y, mat.options = mat.options, store.oob = T, seed = seed, num.cores = 1)
    Yhat <- OOBPredict(X, forest, num.cores = 1)
    oob.errors[i] <- sum(Y != Yhat) / length(Yhat)
  }

  return(oob.errors)
}

oob.errors.rerf <- runExperiment(random.matrix = 'binary', n.samples = n.samples)
oob.errors.rf <- runExperiment(random.matrix = 'rf', n.samples = n.samples)
```

```{r}
df <- data.frame(rep(n.samples, 2), c(oob.errors.rerf, oob.errors.rf), c(rep('Rerf', length(n.samples)), rep('RF', length(n.samples))))
colnames(df) <- c('n.samples', 'oob.errors', 'classifier')

ggplot(data = df, aes(x = n.samples, y = oob.errors, color = classifier, shape = classifier)) + 
  geom_point(alpha = 0.75, size = 1.5) +  
  scale_x_continuous(trans='log10') + 
  labs(x = "Number of Samples", y = "Out of Bag Error", title = "Performance of Rerf vs RF")
```
