---
title: "Random/Randomer Forest Bootstrap vs Subsample"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r randomForest}
# evaluate classifiers on benchmark datasets

rm(list = ls())
options(scipen = 999)

library(randomForest)

# Parameters

# For local
#rerfPath <- "./"
#dataPath <- "./Data/processed/"
#source(paste0(rerfPath, "R/Code/Utils/GetFolds.R"))
#source(paste0(rerfPath, "R/Code/Utils/Utils.R"))

# For MARCC
rerfPath <- "~/work/jaewon/"
dataPath <- "~/work/jaewon/RandomerForest/Data/uci/processed/"
source(paste0(rerfPath, "RandomerForest/R/Utils/GetFolds.R"))
source(paste0(rerfPath, "RandomerForest/R/Utils/Utils.R"))

classifiers <- c("rf-bag", "rf-subsample")
nCl <- length(classifiers)

seed <- 20180626L

set.seed(seed = seed)

testError <- list()
OOBError <- list()
trainTime <- list()
testTime <- list()
bestIdx <- list()
params <- list()


dataSet <- "abalone"
#dataSets <- read.table(paste0(dataPath, "names.txt"))[[1]]

# Set variables
testError[[dataSet]] <- vector(mode = "list", length = nCl)
names(testError[[dataSet]]) <- classifiers
OOBError[[dataSet]] <- vector(mode = "list", length = nCl)
names(OOBError[[dataSet]]) <- classifiers
trainTime[[dataSet]] <- vector(mode = "list", length = nCl)
names(trainTime[[dataSet]]) <- classifiers
testTime[[dataSet]] <- vector(mode = "list", length = nCl)
names(testTime[[dataSet]]) <- classifiers
bestIdx[[dataSet]] <- vector(mode = "list", length = nCl)
names(bestIdx[[dataSet]]) <- classifiers
params[[dataSet]] <- vector(mode = "list", length = nCl)
names(params[[dataSet]]) <- classifiers

# Data wrangling
X <- as.matrix(read.table(paste0(dataPath, "data/", dataSet, ".csv"), header = F, sep = ",", quote = "", row.names = NULL))

p <- ncol(X) - 1L
n <- nrow(X)

Y <- as.integer(X[, p + 1L]) + 1L
X <- X[, -(p + 1L)]

# remove columns with zero variance
X <- X[, apply(X, 2, function(x) any(as.logical(diff(x))))]
# mean-center and scale by sd
X <- scale(X)

# Get folds
fold <- GetFolds(paste0(dataPath, "cv_partitions/", dataSet, "_partitions.txt"))
nFolds <- length(fold)

print(paste0("Evaluting Dataset: ", dataSet))
cat("\n")

for (m in classifiers) {
  # Parameter tuning
  if (m == "rf-bag") {
    replace <- T
  } else if (m == "rf-subsample") {
    replace <- F
  }
  
  # Control for different number of feature selection
  if (p < 5) {
    mtrys <- 1:p
  } else {
    mtrys <- ceiling(p^c(1 / 4, 1 / 2, 3 / 4, 1))
    print(paste0("Mtrys: ", mtrys))
  }
  
  if (n >= 1000) {
    nodesize <- ceiling(n * 0.002)
  } else {
    nodesize <- 1
  }
  
  params[[dataSet]][[m]] <- list(replace = replace, mtrys = mtrys, nodesize = nodesize)
  
  size <- length(mtrys)
  OOBErrors <- matrix(as.double(rep(NA, size)), ncol = nFolds, nrow = size)
  testErrors <- matrix(as.double(rep(NA, size)), ncol = nFolds, nrow = size)
  
  print(paste0("evaluating model: ", m))
  for (fold.idx in seq.int(nFolds)) {
    print(paste0("fitting fold: ", fold.idx))
    
    data <- splitData(X, Y, fold, fold.idx)
    
    for (mtrys.idx in seq.int(length(mtrys))) {
      model <- randomForest(data$X.train, data$y.train, 
                            mtry = mtrys[mtrys.idx], 
                            replace = replace, 
                            nodesize = nodesize)
      
      OOBErrors[mtrys.idx, fold.idx] <- model$err.rate[, 1][length(model$err.rate[, 1])]
      testErrors[mtrys.idx, fold.idx] <- computePredictions(model, data$X.test, data$y.test)
    }
  }
  
  OOBError[[dataSet]][[m]] <- OOBErrors
  testError[[dataSet]][[m]] <- testErrors
}

save(OOBError, testError, file = paste0(rerfPath, "RandomerForest/R/Result/2018.06.26/", dataSet, "_2018_06_26.RData"))
```


```{r rerf, echo=FALSE}
# evaluate classifiers on benchmark datasets

rm(list=ls())
options(scipen = 999)

library(rerf)
library(AUC)
library(dummies)
library(R.utils)

date <- "2018.06.30/"

## For MARCC
rerfPath <- "~/work/jaewon/"
dataPath <- "~/work/jaewon/RandomerForest/Data/uci/processed/"
source(paste0(rerfPath, "RandomerForest/R/Utils/RerFEval.R"))
source(paste0(rerfPath, "RandomerForest/R/Utils/GetCatMap.R"))
source(paste0(rerfPath, "RandomerForest/R/Utils/GetFolds.R"))

## For local
# rerfPath <- "./"
# dataPath <- "./Data/uci/processed/"
# source(paste0(rerfPath, "R/Utils/RerFEval.R"))
# source(paste0(rerfPath, "R/Utils/GetCatMap.R"))
# source(paste0(rerfPath, "R/Utils/GetFolds.R"))


testError <- list()
testAUC <- list()
OOBError <- list()
OOBAUC <- list()
trainTime <- list()
OOBTime <- list()
testTime <- list()
treeStrength <- list()
treeCorr <- list()
numNodes <- list()
bestIdx <- list()
params <- list()

dataSet <- "abalone"
fold <- GetFolds(paste0(dataPath, "cv_partitions/", dataSet, "_partitions.txt"))
nFolds <- length(fold)
X <- as.matrix(read.table(paste0(dataPath, "data/", dataSet, ".csv"), header = F, sep = ",", quote = "", row.names = NULL))
catMap <- NULL
p <- ncol(X) - 1L
p.ohe <- p
Y <- as.integer(X[, p + 1L]) + 1L
X <- X[, -(p + 1L)]
# remove columns with zero variance
X <- X[, apply(X, 2, function(x) any(as.logical(diff(x))))]
# mean-center and scale by sd
X <- scale(X)
p <- ncol(X)

## Parameters
nTrees <- 500L
min.parent <- 6L
max.depth <- ceiling(log2(nrow(X) * 0.8))
bagging <- 1 / exp(1)
replacement <- T
supervised <- 0
num.cores <- 24L
seed <- 20180629L
timeout <- 500

## Classifiers
classifiers <- c("rerf-bag", "rerf-subsample")
nCl <- length(classifiers)

testError[[dataSet]] <- vector(mode = "list", length = nCl)
names(testError[[dataSet]]) <- classifiers
testAUC[[dataSet]] <- vector(mode = "list", length = nCl)
names(testAUC[[dataSet]]) <- classifiers
OOBError[[dataSet]] <- vector(mode = "list", length = nCl)
names(OOBError[[dataSet]]) <- classifiers
OOBAUC[[dataSet]] <- vector(mode = "list", length = nCl)
names(OOBAUC[[dataSet]]) <- classifiers
trainTime[[dataSet]] <- vector(mode = "list", length = nCl)
names(trainTime[[dataSet]]) <- classifiers
OOBTime[[dataSet]] <- vector(mode = "list", length = nCl)
names(OOBTime[[dataSet]]) <- classifiers
testTime[[dataSet]] <- vector(mode = "list", length = nCl)
names(testTime[[dataSet]]) <- classifiers
numNodes[[dataSet]] <- vector(mode = "list", length = nCl)
names(numNodes[[dataSet]]) <- classifiers
bestIdx[[dataSet]] <- vector(mode = "list", length = nCl)
names(bestIdx[[dataSet]]) <- classifiers
params[[dataSet]] <- vector(mode = "list", length = nCl)
names(params[[dataSet]]) <- classifiers

print(dataSet)

for (m in classifiers) {
  if (m == "rerf-bag" || m == "rerf-subsample") {
    random.matrix <- "binary"
    if (p < 5) {
      # mtrys <- c(1:p, p^2)
      mtrys <- p^2
    } else if (p >= 5 && p <= 100) {
      #mtrys <- ceiling(p^c(1/4, 1/2, 3/4, 1))
      mtrys <- ceiling(p^2)
    } else {
      # mtrys <- ceiling(p^c(1/4, 1/2, 3/4, 1))
      mtrys <- ceiling(p^1.5)
    }
    sparsity <- (1:min(p-1, 5))/p
    # prob <- c(0.5, 0.75, 0.9)
    prob <- 0.5
    
    if (m == "rerf-subsample") {
      replacement <- F
    }
  }
  
  params[[dataSet]][[m]] <- list(trees = nTrees, random.matrix = random.matrix, d = mtrys, sparsity = sparsity, prob = prob, rotate = rotate,
                                 rank.transform = rank.transform, min.parent = min.parent, max.depth = max.depth, num.cores = num.cores,
                                 seed = seed, cat.map = catMap, supervised = supervised, replacement = replacement, bagging = bagging)
  
  testError[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                      nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  testAUC[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                    nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  OOBError[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                     nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  OOBAUC[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                   nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  trainTime[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                      nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  OOBTime[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                    nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  testTime[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                     nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  numNodes[[dataSet]][[m]] <- matrix(as.double(rep(NA, nFolds*length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))),
                                     nrow = nFolds, ncol = length(sparsity)*length(mtrys)*length(supervised)*max(length(prob), 1))
  bestIdx[[dataSet]][[m]] <- as.integer(rep(NA, nFolds))
  
  print(params[[dataSet]][[m]])
  
  # loop over folds
  for (k in seq.int(nFolds)) {
    print(paste0("fold ", k))
    
    trainIdx <- unlist(fold[-k])
    testIdx <- fold[[k]]
    
    # evaluate models
    res <- RerFEval(X[trainIdx, ], Y[trainIdx], X[testIdx, ], Y[testIdx], params[[dataSet]][[m]], timeout = timeout)
    
    testError[[dataSet]][[m]][k, ] <- res$testError
    testAUC[[dataSet]][[m]][k, ] <- res$testAUC
    OOBError[[dataSet]][[m]][k, ] <- res$oobError
    OOBAUC[[dataSet]][[m]][k, ] <- res$oobAUC
    trainTime[[dataSet]][[m]][k, ] <- res$trainTime
    OOBTime[[dataSet]][[m]][k, ] <- res$oobTime
    testTime[[dataSet]][[m]][k, ] <- res$testTime
    numNodes[[dataSet]][[m]][k, ] <- res$numNodes
    bestIdx[[dataSet]][[m]][k] <- res$best.idx
    
    save(testError, testAUC, OOBError, OOBAUC, trainTime, OOBTime, testTime, numNodes, bestIdx, params, 
         file = paste0(rerfPath, "RandomerForest/R/Experiments/", date, "Results/", dataSet, ".RData"))
  }
}

```